server:
  port: 8082
spring:
  kafka:
    topic:  "library-events"
      
    producer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:  
        bootstrap-servers:  localhost:9092,localhost:9093,localhost:9094